use 96r;
show tables;
select * from student6;
select upper(name) from student6;
 select lower(name) from student6;
 select upper("chandu") as uppercase;
 select concat("navider","rathod");
 select concat("navider","rathod") as student6;
 select concat("navider"," ","rathod") as student6;
 select concat(name,"rathod") from student6;
 select substring("navider",1,4);
  select left("chandrika",5);
  select right("chandrika",5);
  select replace("chandrika","r","u");
  select trim("    navider");
  select rtrim("    navider");
   select ltrim("    navider");
select length(name) from employee;
select instr("v","ravi");
select instr("ramya","a");
 select locate("a","ramya");
 select lpad("123",5,9);
 select  rpad("123",5,0);
 select now();
select time(now());
 select month(now());
 select dayname(now());
 select monthname(now());

